### ISSUE TITLE
DCV: Unexpected error

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#47]
And when selecting second region and clicking on refresh,
![image](https://cloud.githubusercontent.com/assets/718827/13662332/f1209c08-e699-11e5-8814-bbe19cf722a1.png)

```
TypeError: Cannot create property 'label' on string 'Počet lidí daného pohlaví a věku v daném okrese ke konci daného roku.'
    at http://demo.viz.linkedpipes.com/assets/javascripts/angular/ldvm/filters/labelFilter.js:12:38
    at label (http://demo.viz.linkedpipes.com/assets/javascripts/angular/datacube/controllers/controllers.js:23:45)
    at queryResultsLoaded (http://demo.viz.linkedpipes.com/assets/javascripts/angular/datacube/controllers/controllers.js:430:46)
    at DataCubeService.slices.$scope.queryingDataset (http://demo.viz.linkedpipes.com/assets/javascripts/angular/datacube/controllers/controllers.js:410:29)
    at http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular-resource.js:587:32
    at wrappedCallback (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:11573:81)
    at http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:11659:26
    at Scope.$eval (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:12702:28)
    at Scope.$digest (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:12514:31)
    at Scope.$apply (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:12806:24) undefined
```

**Comment by jakubklimek** [comment]
Maybe because one of the regions was dereferenced and one not?

**Comment by jirihelmich** [comment]
Rather seems like a developer going crazy. Exemplary DCV was used as the input?

**Comment by jakubklimek** [comment]
Yes
