### ISSUE TITLE
Undefined. Terminating

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/visualizations#49]
I drag & dropped files in
[test.zip](https://github.com/linkedpipes/visualizations/files/199451/test.zip)
into the drop zone.
1) file names are not separated
2) when clicking on Visualize, I get:
![image](https://cloud.githubusercontent.com/assets/718827/14205159/748ce274-f809-11e5-8a13-e423e4f93bcc.png)

**Comment by jakubklimek** [comment]
The last file contained some .ttl files which were in fact TriG files. I tried again, and got:
![image](https://cloud.githubusercontent.com/assets/718827/14205223/fa2f0038-f809-11e5-9c83-08aeea4ccca3.png)
Instead of 6 different files, I got 6 times the same one

**Comment by jakubklimek** [comment]
In the console, there was 

```
/webjars/angularjs/1.2.26/angular.js:10072 RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at toJson (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:1121:15)
    at defaults.defaults.transformRequest (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:7495:56)
    at http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:7436:12
    at forEach (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:325:18)
    at transformData (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:7435:3)
    at serverRequest (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:8072:23)
    at wrappedCallback (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:11573:81)
    at http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:11659:26 undefined(anonymous function) @ /webjars/angularjs/1.2.26/angular.js:10072
/webjars/angularjs/1.2.26/angular.js:10072 TypeError: Cannot read property 'ignoreLoadingBar' of undefined
    at responseError (http://demo.viz.linkedpipes.com/webjars/angular-loading-bar/0.5.1/loading-bar.js:129:32)
    at wrappedErrback (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:11582:78)
    at wrappedErrback (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:11582:78)
    at http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:11715:76
    at Scope.$eval (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:12702:28)
    at Scope.$digest (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:12514:31)
    at Scope.$apply (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:12806:24)
    at HTMLButtonElement.<anonymous> (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:19141:23)
    at http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:2853:10
    at forEach (http://demo.viz.linkedpipes.com/webjars/angularjs/1.2.26/angular.js:325:18) undefined
```

**Comment by jirihelmich** [comment]
Need to change how upload works as it seems that for large files, this is not suitable. I use HTML5 file reader and assemble a JSON from base64 data. Not applicable to 200MBs, though.
